// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using personaapi_dotnet.Context;

#nullable disable

namespace personaapi_dotnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240421224444_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("personaapi_dotnet.Models.Estudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonaCc")
                        .HasColumnType("int");

                    b.Property<int>("PersonaCedula")
                        .HasColumnType("int");

                    b.Property<string>("ProfesionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfesionId1")
                        .HasColumnType("int");

                    b.Property<string>("Universidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaCc");

                    b.HasIndex("ProfesionId1");

                    b.ToTable("Estudios");
                });

            modelBuilder.Entity("personaapi_dotnet.Models.Persona", b =>
                {
                    b.Property<int>("Cc")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cc");

                    b.HasIndex("Cc")
                        .IsUnique();

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("personaapi_dotnet.Models.Profesion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Profesiones");
                });

            modelBuilder.Entity("personaapi_dotnet.Models.Telefono", b =>
                {
                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Operador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonaCc")
                        .HasColumnType("int");

                    b.Property<int>("PersonaCedula")
                        .HasColumnType("int");

                    b.HasKey("Numero");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("PersonaCc");

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("personaapi_dotnet.Models.Estudio", b =>
                {
                    b.HasOne("personaapi_dotnet.Models.Persona", null)
                        .WithMany("Estudios")
                        .HasForeignKey("PersonaCc");

                    b.HasOne("personaapi_dotnet.Models.Profesion", null)
                        .WithMany("Estudios")
                        .HasForeignKey("ProfesionId1");
                });

            modelBuilder.Entity("personaapi_dotnet.Models.Telefono", b =>
                {
                    b.HasOne("personaapi_dotnet.Models.Persona", null)
                        .WithMany("Telefonos")
                        .HasForeignKey("PersonaCc");
                });

            modelBuilder.Entity("personaapi_dotnet.Models.Persona", b =>
                {
                    b.Navigation("Estudios");

                    b.Navigation("Telefonos");
                });

            modelBuilder.Entity("personaapi_dotnet.Models.Profesion", b =>
                {
                    b.Navigation("Estudios");
                });
#pragma warning restore 612, 618
        }
    }
}
